name: Deploy

on:
 push:
  branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install npm dependencies
      run: yarn install
    - name: Launch test
      run: yarn test
    - name: Lint files
      run: yarn lint
    - name: Run build task
      run: yarn run build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.0.8
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
